# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests-Passing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #commit:
   # branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.0-rc.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8 
        pip install pyflakes 
        pip install pylint 
        pip install radon
        pip install anybadge
    - name: Run_static_analysis_tools
      run: |
        autopep8 --aggressive --aggressive --aggressive --recursive --diff ./hw2
        pyflakes ./hw2
        pylint ./hw2
        radon cc ./hw2
        radon mi ./hw2
        radon raw ./hw2
    - name: Test_with_pytest
      run: |
        pip install pytest pytest-cov
        pytest ./hw2/tests.py
    - name: badges
      if: always()
      run: |
        rm ./hw2/pylint.svg
        anybadge -l pylint -v 3.33 -f ./hw2/pylint.svg 2=red 4=orange 8=yellow 10=green
        anybadge -l pyflakes -v 3.20 -f ./hw2/pyflakes.svg --color='#97CA00'
        anybadge -l autopep8 -v 2.13 -f ./hw2/autopep8.svg --color='#97CA00'
        git config --global user.email "anirudhkaluri@gmail.com"
        git config --global user.name "Anirudh Kaluri"
        git add .
        git commit -m "badges updated"
        git push
    
